### ISSUE TITLE
make: *** [Adjacency-Circunference] Error 1

### ISSUE THREAD

**Issue by ricoms** [GIBIS-UNIFESP/BIAL#1]
Olá,

Segui as orientações descritas aqui: https://gibis-unifesp.github.io/BIAL/html/index.html a única coisa que fiz diferente foi criar um branch de nome _IFT,_ para não editar direto no _master_.

Ao aplicar o comando **make** dentro da pasta _tst/_ obtive a seguinte mensagem de erro:
```sh
export LD_LIBRARY_PATH=../build/linux/release/lib
g++ -Wl,--no-as-needed --std=c++0x -Wall -Wno-unused-function -Wno-literal-conversion -I../bial/inc -I../bial/src -I../bial/SLIC/inc -I../bial/cpplex/inc -I../bial/lsh/inc -DREAL_FLOAT -O3 -o ./bin/Adjacency-Circunference ./src/Adjacency-Circunference.cpp -L../build/linux/release/lib -lbial -L../bial/SLIC/obj/* -L../bial/cpplex/obj/* -L../bial/lsh/obj/* -fopenmp -lpthread -lz -lm
/usr/bin/ld: cannot find -lbial
collect2: error: ld returned 1 exit status
Makefile:87: recipe for target 'Adjacency-Circunference' failed
make: *** [Adjacency-Circunference] Error 1
```
à partir daqui não soube mais o que fazer. Meu compilador g++ está na versão (5.4.0) acima da versão indicada e meu SO é Ubuntu 16.04.

Como prosseguir?

**Comment by ricoms** [comment]
Acredito que está faltando o procedimento para instalar a biblioteca, é isso?

**Comment by lellisls** [comment]
Na hora de compilar no qtcreator, vc selecionou o modo debug ou release?
Tenta fazer esse make usando o comando make debug=1 IFT....

Em sáb, 22 de abr de 2017 11:49, Ricardo Manhães Savii <
notifications@github.com> escreveu:

**Comment by ricoms** [comment]
Não utilizei o qtcreator, estou direto no terminal

Observação: novato em projetos em Cpp aqui*

**Comment by lellisls** [comment]
Vc chegou a compilar a Bial antes? Olha a pasta BIAL/build/linux/release e
a pasta BIAL/Linux/debug e olha se a libbial.so foi compilada.

Em sáb, 22 de abr de 2017 11:56, Ricardo Manhães Savii <
notifications@github.com> escreveu:

**Comment by ricoms** [comment]
as pastas _BIAL/build_ e _BIAL/Linux_ não existem no projeto.
Tampouco encontrei o arquivo libbial.so dentro do projeto.

Eu só fiz o _clone_ do projeto e comecei a seguir a documentação do link no meu primeiro comentário.

**Comment by ricoms** [comment]
@lellisls obrigado pelo suporte! :+1: 

estou tentando entender aqui como instala, agradeço se puder me orientar

**Comment by lellisls** [comment]
Entra na pasta BIAL/build e dá um make

Em sáb, 22 de abr de 2017 12:14, Ricardo Manhães Savii <
notifications@github.com> escreveu:

**Comment by ricoms** [comment]
A bial disponível aqui neste repositório é a versão que foi passada em sala de aula?
pergunto pq não existe pasta **BIAL/build** neste repositório

**Comment by lellisls** [comment]
** entra na pasta BIAL/bial e dá um make.. ou então instala o qtcreator,
pelo pacote qt-sdk no Ubuntu ou baixando no site qt.io

Em sáb, 22 de abr de 2017 12:44, Lucas Santana <lucaslellis777@gmail.com>
escreveu:

**Comment by lellisls** [comment]
Na aula o professor já tinha a Bial pré-compilada , mas no github ela não
está disponível

Em sáb, 22 de abr de 2017 12:46, Ricardo Manhães Savii <
notifications@github.com> escreveu:

**Comment by ricoms** [comment]
resultado do comando **make** dentro da pasta BIAL/bial:
```
/usr/bin/qmake-qt5 CONFIG+=release -o Makefile bial.pro
make: /usr/bin/qmake-qt5: Command not found
Makefile:1189: recipe for target 'Makefile' failed
make: *** [Makefile] Error 127
```
Tem na documentação como fazer a pré-compilação da BIAL? Ou seria só esse procedimento acima?
o qt.io é pago, se puder viver sem ele, prefiro.

**Comment by lellisls** [comment]
Acho que esse makefile tá zoado, pq ele exige que tenha o qmake
instalado... Mas o qt não é pago não.  Baixa a versão Open Source..
http://qt.io/download-opensource.

Em sáb, 22 de abr de 2017 12:53, Ricardo Manhães Savii <
notifications@github.com> escreveu:

**Comment by ricoms** [comment]
No site não tem mais disponível essa versão:

![screenshot from 2017-04-22 13-00-36](https://cloud.githubusercontent.com/assets/5393732/25306005/c2fc5eee-275b-11e7-995f-6375e4578746.png)

**Comment by ricoms** [comment]
Estou instalando o free-trial aqui, mas fica então a pendência de eliminar o qt... depois do free-trial não serei mais capaz de usar sua biblioteca sem precisar pagar o software de terceiros

**Comment by lellisls** [comment]
https://www.qt.io/download-open-source/

Em sáb, 22 de abr de 2017 13:03, Ricardo Manhães Savii <
notifications@github.com> escreveu:

**Comment by lellisls** [comment]
Calma, qt é aberto. Só procurar o link correto

Em sáb, 22 de abr de 2017 13:04, Lucas Santana <lucaslellis777@gmail.com>
escreveu:

**Comment by ricoms** [comment]
o **master.pro** não inclui a pasta **tst/**,
ao abrir no _qtcreator_ meu projeto só possui as pastas _bial/_ e _BIAL_GUI/_ é isso mesmo?

![screenshot from 2017-04-22 13-26-36](https://cloud.githubusercontent.com/assets/5393732/25306231/599a9106-275f-11e7-8193-5c5f6243fee9.png)

Onde posso colocar meu código de teste para imitar os resultados do artigo? Os testes que criarmos será incluído posteriormente no repositório?

**Comment by ricoms** [comment]
O erro original da issue permanece, a pasta **build** foi criada pelo _qtcreator_.

Mas ao aplicar o comando **make** dentro da pasta _tst/_ ocorre o mesmo erro:

```sh
export LD_LIBRARY_PATH=../build/linux/release/lib
g++ -Wl,--no-as-needed --std=c++0x -Wall -Wno-unused-function -Wno-literal-conversion -I../bial/inc -I../bial/src -I../bial/SLIC/inc -I../bial/cpplex/inc -I../bial/lsh/inc -DREAL_FLOAT -O3 -o ./bin/Adjacency-Circunference ./src/Adjacency-Circunference.cpp -L../build/linux/release/lib -lbial -L../bial/SLIC/obj/* -L../bial/cpplex/obj/* -L../bial/lsh/obj/* -fopenmp -lpthread -lz -lm
/usr/bin/ld: cannot find -lbial
collect2: error: ld returned 1 exit status
Makefile:87: recipe for target 'Adjacency-Circunference' failed
make: *** [Adjacency-Circunference] Error 1
```

**Comment by lellisls** [comment]
No qtcreator vc precisa selecionar o modo debug ou release, e em seguida
clicar na setinha pra compilar a libbial.Só

Em seguida, o make da pasta tst é feito de forma independente.
Se vc compilar no modo debug, terá que fazer make debug=1, caso contrário
não precisa..

Em sáb, 22 de abr de 2017 13:39, Ricardo Manhães Savii <
notifications@github.com> escreveu:

**Comment by ricoms** [comment]
ok, compilei em modo release e o _qtcreator_ criou uma pasta **build-master-Desktop_Qt_5_8_0_GCC_64bit-Release**, porém dentro da pasta só há as subpastas **BIAL-GUI/** e **bial/**.

Eu quero começar a escrever meu código na pasta **tst/**. Basta eu copiar a pasta **tst/** da pasta que clonei para essa nova pasta do _qtcreator_, e começar a escrever código?

**Comment by ricoms** [comment]
o comando **make** dentro da pasta _/tst/_ funcionou. Deu vários **warnings**... mas foi.

Agora só falta eu ser capaz de criar um novo arquivo, tipo **IFT_blá.cpp**, dentro da pasta _/tst/src/_ e conseguir compilar ele.

Como último favor, estou te enchendo muito o saco já, quais são as orientações para eu criar um novo arquivo e compilar o experimento?

**Comment by lellisls** [comment]
Cria um novo arquivo IFT_ricardo.cpp na pasta src.

Daí edita o makefile, copiando os comandos de algum dos exemplos, como
Image-Compare

Por último faça o export LD_LIBRARY_PATH=../build/linux/release/lib e
./bin/IFT_ricardo

Em sáb, 22 de abr de 2017 14:12, Ricardo Manhães Savii <
notifications@github.com> escreveu:

**Comment by ricoms** [comment]
Beleza,

Muito obrigado @lellisls! Vou encerrar esta _issue_, o **make** ainda está rolando aqui, mas acredito que a _issue_ principal está fechada.

Vou ver se consigo começar a codificar, assim que terminar o **make**.
