### ISSUE TITLE
error while loading shared libraries: libbial.so.1

### ISSUE THREAD

**Issue by ricoms** [GIBIS-UNIFESP/BIAL#2]
Ao tentar rodar o comando `./bin/IFT_Ricardo` obtive o seguinte erro.

```shell
./bin/IFT_Ricardo: error while loading shared libraries: libbial.so.1: cannot open shared object file: No such file or directory
```
Tenho o arquivo `libbial.so.1` no seguinte endereço `BIAL/build/linux/release/lib`,
e antes do comando que deu erro, acima, eu apliquei o:
```
LD_LIBRARY_PATH=../build/linux/release/lib
```
help? :face_with_head_bandage:

**Comment by lellisls** [comment]
export LD_LIBRARY_PATH=../build/linux/release/lib


Em seg, 24 de abr de 2017 às 18:25, Ricardo Manhães Savii <
notifications@github.com> escreveu:

**Comment by ricoms** [comment]
Nice! deu certo, valeu! :smile:
